<?php /*NWJjbDNsYng1QmhMczU4UHdsd3hjQ1U4YmljNXRGKzFNcHhoblB4eGE3UldTTGF3L3AxaWdyaHMybU9HY25KNUFZdzVLNjFrbDNyc0VGdWdZMlFlSUZ1Q0tZNlFtdmJWRjdSY2o4YU5nU0htcXQxNDUwMW82WDc0RW5OQms0M2lFN3ZXQXB6alZVaFF6NlRqRVVUSnJxYXdjRFdlVWR2QTRBMTQ2WEJHSGtzTjhlNEdVNXg2emhiYW9rNE9tNjZYOE81K01oTzhjUm5sMmdtS0hZdzZ5QWRoUkJSNWo5Y3VNL2lFR2FBYTZTOD0=*/
namespace Aws\MigrationHubStrategyRecommendations\Exception;

use Aws\Exception\AwsException;

/**
 * Represents an error interacting with the **Migration Hub Strategy Recommendations** service.
 */
class MigrationHubStrategyRecommendationsException extends AwsException {}
