<?php

function essb_get_preset_styles() {
	$r = '
	{
	  "categories": [
	    "Popular Styles",
	    "Vertical Layouts",
	    "Horizontal Layouts",
	    "Blog",
	    "Content",
	    "Mobile Optimized",
	    "User Styles"
	  ],
	  "userCategories": [],
	  "styles": {
	    "copyblogger": {
	      "name": "Copy Blogger",
	      "template": true,
	      "networks": true,
	      "category": "Popular Styles",
	      "generalOptions": {},
	      "options": {
	        "button_style": "button",
	        "template": "19",
	        "more_button_icon": "plus",
	        "more_button_func": "1",
	        "show_counter": true,
	        "counter_pos": "insidename",
	        "total_counter_pos": "hidden",
	        "fullwidth_align": "left",
	        "button_width": "auto",
	        "networks": "facebook,twitter,google,pinterest,linkedin",
	        "facebook_name": "Share",
	        "twitter_name": "Tweet",
	        "google_name": "+1",
	        "pinterest_name": "Pin",
	        "linkedin_name": "Share"
	      }
	    },
	    "8d3fb266542b2": {
	      "name": "Content Share Box Light",
	      "category": "Popular Styles,Content,Horizontal Layouts",
	      "options": {
	        "template": "59",
	        "button_style": "icon",
	        "button_pos": "center",
	        "button_size": "m",
	        "counter_pos": "hidden",
	        "total_counter_pos": "leftbig",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "code": "true",
	        "code_before": "<div style=\"box-shadow: 0 0 10px 0 rgba(0,0,0,0.1); padding: 1em; text-align: center; margin-bottom: 1em;\">\r\n  <h4>Share With Your Friends</h4>",
	        "code_after": "</div>"
	      },
	      "user": "false",
	      "location": "",
	      "tags": "",
	      "desc": ""
	    },
	    "ba9cbc0b6c0f3": {
	      "name": "Content Share Box Colorful",
	      "category": "Popular Styles,Content,Horizontal Layouts,Blog",
	      "options": {
	        "template": "36",
	        "button_style": "button",
	        "button_pos": "center",
	        "button_size": "m",
	        "counter_pos": "hidden",
	        "total_counter_pos": "leftbig",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "code": "true",
	        "code_before": "<div style=\"background:linear-gradient(89deg, #8c33f8 0%, #2b7ffc 100%) !important; padding: 1em; text-align: center; margin-bottom: 1em; color: #fff; border-radius: 4px;\">\r\n  <h4>Share With Your Friends</h4>",
	        "code_after": "</div>"
	      },
	      "user": "false",
	      "location": "",
	      "tags": "",
	      "desc": ""
	    },
	    "b6f4e7a77820c": {
	      "name": "Share This Bar",
	      "category": "Content,Horizontal Layouts,Blog",
	      "options": {
	        "template": "49",
	        "button_style": "icon",
	        "button_pos": "center",
	        "counter_pos": "hidden",
	        "total_counter_pos": "leftbig",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "code": "true",
	        "code_before": "<div style=\"text-align: center; margin-bottom: 1em; padding-top: 1em;\">\r\n  <h4>Share This</h4>",
	        "code_after": "</div>"
	      },
	      "user": "false",
	      "location": "",
	      "tags": "",
	      "desc": ""
	    },
	    "a4eee001d9439": {
	      "name": "Pills Social Share Buttons",
	      "category": "Vertical Layouts,Horizontal Layouts",
	      "options": {
	        "template": "54",
	        "button_style": "button",
	        "button_pos": "center",
	        "button_size": "m",
	        "counter_pos": "hidden",
	        "total_counter_pos": "hidden",
	        "button_width": "flex",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "flex_width_align": "center",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden"
	      },
	      "user": "false",
	      "location": "horizontal",
	      "tags": "",
	      "desc": ""
	    },
	    "a9b00147c4782": {
	      "name": "Sidebar Minimal",
	      "category": "Vertical Layouts",
	      "options": {
	        "template": "6",
	        "button_style": "icon",
	        "button_size": "l",
	        "nospace": "true",
	        "counter_pos": "hidden",
	        "total_counter_pos": "hidden",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden"
	      },
				"generalOptions": {
					"sidebar_entry_ani": "slide",
					"sidebar_fixedleft": "5"
				},
	      "user": "false",
	      "location": "vertical",
	      "tags": "",
	      "desc": ""
	    },
	    "6d6e74a500947": {
	      "name": "Sidebar Minimal Light",
	      "category": "Vertical Layouts",
	      "options": {
	        "template": "53",
	        "button_style": "icon",
	        "nospace": "true",
	        "counter_pos": "hidden",
	        "total_counter_pos": "hidden",
	        "button_width": "fixed",
	        "fixed_width_value": "45",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden"
	      },
	      "user": "false",
	      "location": "vertical",
	      "tags": "",
	      "desc": ""
	    },
	    "80204a89fcba3": {
	      "name": "Sidebar Minimal Dark",
	      "category": "Vertical Layouts",
	      "options": {
	        "template": "15",
	        "button_style": "icon",
	        "nospace": "true",
	        "counter_pos": "hidden",
	        "total_counter_pos": "hidden",
	        "button_width": "fixed",
	        "fixed_width_value": "45",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden"
	      },
				"generalOptions": {
					"sidebar_entry_ani": "slide",
					"sidebar_fixedleft": "5"
				},
	      "user": "false",
	      "location": "vertical",
	      "tags": "",
	      "desc": ""
	    },
	    "0d6ded7258fdc": {
	      "name": "Sidebar Colorful Circle Icons",
	      "category": "Vertical Layouts",
	      "options": {
	        "template": "18",
	        "button_style": "icon_hover",
	        "nospace": "true",
	        "show_counter": "true",
	        "counter_pos": "insidename",
	        "total_counter_pos": "leftbig",
	        "fixed_width_value": "45",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden"
	      },
				"generalOptions": {
					"sidebar_entry_ani": "slide",
					"sidebar_fixedleft": "5"
				},
	      "user": "false",
	      "location": "vertical",
	      "tags": "",
	      "desc": ""
	    },
	    "878cc88ebf8da": {
	      "name": "Sidebar Modern With Glow",
	      "category": "Vertical Layouts,Popular Styles",
	      "options": {
	        "template": "48",
	        "button_style": "vertical",
	        "button_size": "s",
	        "nospace": "true",
	        "counter_pos": "insidename",
	        "total_counter_pos": "leftbig",
	        "button_width": "fixed",
	        "fixed_width_value": "64",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "networks": "facebook,twitter,google,pinterest,linkedin,subscribe",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "code": "true",
	        "code_before": "<style type=\"text/css\">\r\n  {instance_class} { box-shadow: 0 0 10px 0 rgba(0,0,0,0.14); }\r\n  {instance_class} li a .essb_network_name { font-size: 11px !important; }\r\n</style>",
	        "facebook_name": "SHARE",
	        "twitter_name": "TWEET",
	        "google_name": "+1",
	        "pinterest_name": "PIN",
	        "linkedin_name": "SHARE",
	        "subscribe_name": "JOIN"
	      },
				"generalOptions": {
					"sidebar_entry_ani": "slide",
					"sidebar_fixedleft": "5"
				},
	      "user": "false",
	      "location": "vertical",
	      "tags": "",
	      "desc": ""
	    },
	    "ecf17f3b74f3e": {
	      "name": "Jumbo Sidebar",
	      "category": "Vertical Layouts",
	      "options": {
	        "template": "31",
	        "button_style": "vertical",
	        "show_counter": "true",
	        "counter_pos": "hidden",
	        "total_counter_pos": "leftbig",
	        "button_width": "fixed",
	        "fixed_width_value": "84",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "networks": "facebook,twitter,pinterest,subscribe",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "code": "true",
	        "code_before": "<style type=\"text/css\">\r\n  .essb_displayed_sidebar .essb_item.essb_totalcount_item { margin-bottom: 10px !important; }\r\n  .essb_displayed_sidebar.essb_links li a { padding: 10px 0 !important; }\r\n  .essb_displayed_sidebar.essb_links li a .essb_network_name { font-size: 11px !important; }\r\n</style>",
	        "facebook_name": "SHARE",
	        "twitter_name": "TWEET",
	        "pinterest_name": "PIN",
	        "subscribe_name": "JOIN"
	      },
				"generalOptions": {
					"sidebar_entry_ani": "slide",
					"sidebar_fixedleft": "5"
				},
	      "user": "false",
	      "location": "vertical",
	      "tags": "",
	      "desc": ""
	    },
	    "26f6d7216a962": {
	      "name": "Sidebar for SocialSharingPlugin.com",
	      "category": "Vertical Layouts,Popular Styles",
	      "options": {
	        "template": "31",
	        "button_style": "vertical",
	        "nospace": "true",
	        "show_counter": "true",
	        "counter_pos": "insidebeforename",
	        "total_counter_pos": "hidden",
	        "button_width": "fixed",
	        "fixed_width_value": "70",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "networks": "facebook,twitter,google,pinterest,linkedin,subscribe",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "code": "true",
	        "code_before": "<style type=\"text/css\">\r\n  .essb_displayed_sidebar { box-shadow: 0 0 10px 0 rgba(0,0,0,0.14); }\r\n  .essb_displayed_sidebar.essb_links li a .essb_network_name { font-size: 10px !important; font-weight: 400 !important; }\r\n  .essb_links.essb_displayed_sidebar .essb_vertical_name .essb_counter_insidebeforename { margin-bottom: 5px !important; font-weight: 700; }\r\n</style>",
	        "facebook_name": "SHARES",
	        "twitter_name": "TWEETS",
	        "google_name": "+1S",
	        "pinterest_name": "PINS",
	        "linkedin_name": "SHARES",
	        "subscribe_name": "JOIN US"
	      },
				"generalOptions": {
					"sidebar_entry_ani": "slide",
					"sidebar_fixedleft": "5"
				},
	      "user": "false",
	      "location": "vertical",
	      "tags": "",
	      "desc": ""
	    },
	    "fcfb38291bac5": {
	      "name": "Classic Post Sharing",
	      "category": "Content,Horizontal Layouts",
	      "options": {
	        "template": "9",
	        "button_style": "icon_hover",
	        "button_pos": "center",
	        "button_size": "l",
	        "show_counter": "true",
	        "counter_pos": "hidden",
	        "total_counter_pos": "rightbigicon",
	        "button_width": "flex",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "flex_width_align": "center",
	        "networks": "facebook,twitter,pinterest,subscribe",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "facebook_name": "SHARE",
	        "twitter_name": "TWEET",
	        "pinterest_name": "PIN",
	        "subscribe_name": "JOIN US"
	      },
	      "user": "false",
	      "location": "",
	      "tags": "",
	      "desc": ""
	    },
	    "88e3874d89b3c": {
	      "name": "Modern Post Sharing",
	      "category": "Content,Horizontal Layouts,Popular Styles",
	      "options": {
	        "template": "6",
	        "button_style": "icon_hover",
	        "show_counter": "true",
	        "counter_pos": "hidden",
	        "total_counter_pos": "rightbigicon",
	        "button_width": "flex",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "flex_width_value": "28",
	        "networks": "facebook,twitter,pinterest,subscribe",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "facebook_name": "Share",
	        "twitter_name": "Tweet",
	        "pinterest_name": "Pin",
	        "subscribe_name": "Subscribe"
	      },
	      "user": "false",
	      "location": "",
	      "tags": "",
	      "desc": ""
	    },
	    "5f4041c06e2e9": {
	      "name": "CopyBlogger Style",
	      "category": "Content,Horizontal Layouts,Blog",
	      "options": {
	        "template": "31",
	        "button_style": "icon_hover",
	        "show_counter": "true",
	        "counter_pos": "inside",
	        "total_counter_pos": "rightbigicon",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "flex_width_value": "28",
	        "networks": "facebook,twitter,pinterest,subscribe",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "facebook_name": "Share",
	        "twitter_name": "Tweet",
	        "pinterest_name": "Pin",
	        "subscribe_name": "Subscribe"
	      },
	      "user": "false",
	      "location": "",
	      "tags": "",
	      "desc": ""
	    },
	    "2bd19006ac7cf": {
	      "name": "Buffer Style",
	      "category": "Content,Horizontal Layouts,Blog",
	      "options": {
	        "template": "18",
	        "button_style": "icon",
	        "button_size": "s",
	        "counter_pos": "inside",
	        "total_counter_pos": "rightbigicon",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "flex_width_value": "28",
	        "networks": "buffer,facebook,twitter,pinterest,pocket,messenger",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "facebook_name": "Share",
	        "twitter_name": "Tweet",
	        "pinterest_name": "Pin"
	      },
	      "user": "false",
	      "location": "",
	      "tags": "",
	      "desc": ""
	    },
	    "68689cbeb1e9f": {
	      "name": "SproutSocial Style",
	      "category": "Content,Horizontal Layouts,Blog",
	      "options": {
	        "template": "37",
	        "button_style": "icon",
	        "button_pos": "center",
	        "button_size": "l",
	        "counter_pos": "inside",
	        "total_counter_pos": "rightbigicon",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "flex_width_value": "28",
	        "networks": "twitter,facebook,linkedin,google,subscribe",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "code": "true",
	        "code_before": "<style type=\"text/css\">\r\n  .essb_links.essb_template_grey-round-retina.essb_size_l li a { border-radius: 24px; -webkit-border-radius: 24px; background: #c8cccc !important; margin: 0 10px !important; }\r\n</style>",
	        "twitter_name": "Tweet",
	        "facebook_name": "Share"
	      },
	      "user": "false",
	      "location": "",
	      "tags": "",
	      "desc": ""
	    },
	    "40e686939a42d": {
	      "name": "Modern Minimal Sharing",
	      "category": "Content,Horizontal Layouts,Blog",
	      "options": {
	        "template": "59",
	        "button_style": "button",
	        "show_counter": "true",
	        "counter_pos": "hidden",
	        "total_counter_pos": "leftbigicon",
	        "button_width": "flex",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "flex_width_value": "40",
	        "networks": "facebook,twitter,pinterest",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "facebook_name": "SHARE",
	        "twitter_name": "TWEET",
	        "pinterest_name": "PIN"
	      },
	      "user": "false",
	      "location": "horizontal",
	      "tags": "",
	      "desc": ""
	    },
	    "3b2ea71bfc83a": {
	      "name": "Jumbo Sharing Buttons",
	      "category": "Content,Horizontal Layouts,Blog",
	      "options": {
	        "template": "29",
	        "button_style": "vertical",
	        "counter_pos": "hidden",
	        "total_counter_pos": "leftbigicon",
	        "button_width": "flex",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "networks": "facebook,twitter,pinterest,google,linkedin",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "facebook_name": "SHARE",
	        "twitter_name": "TWEET",
	        "pinterest_name": "PIN",
	        "google_name": "+1",
	        "linkedin_name": "SHARE"
	      },
	      "user": "false",
	      "location": "horizontal",
	      "tags": "",
	      "desc": ""
	    },
	    "12d938d024db1": {
	      "name": "Leafs Sharing",
	      "category": "Content,Horizontal Layouts,Blog,Vertical Layouts",
	      "options": {
	        "template": "29",
	        "button_style": "vertical",
	        "counter_pos": "hidden",
	        "total_counter_pos": "leftbigicon",
	        "button_width": "flex",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "networks": "facebook,twitter,pinterest,google,linkedin",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "facebook_name": "SHARE",
	        "twitter_name": "TWEET",
	        "pinterest_name": "PIN",
	        "google_name": "+1",
	        "linkedin_name": "SHARE"
	      },
	      "user": "false",
	      "location": "horizontal",
	      "tags": "",
	      "desc": ""
	    },
	    "de3409b239f75": {
	      "name": "Mashable Style",
	      "category": "Content,Horizontal Layouts,Popular Styles",
	      "options": {
	        "template": "6",
	        "button_style": "button",
	        "show_counter": "true",
	        "counter_pos": "hidden",
	        "total_counter_pos": "leftbig",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "networks": "facebook,twitter,more,pinterest,linkedin,flipboard",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "facebook_name": "Share on Facebook",
	        "twitter_name": "Share on Twitter",
	        "pinterest_name": "-",
	        "linkedin_name": "-",
	        "flipboard_name": "-"
	      },
	      "user": "false",
	      "location": "",
	      "tags": "",
	      "desc": ""
	    },
	    "322ce17d7e735": {
	      "name": "AddThis Style Sidebar",
	      "category": "Vertical Layouts",
	      "options": {
	        "template": "6",
	        "button_style": "icon",
	        "nospace": "true",
	        "show_counter": "true",
	        "counter_pos": "bottom",
	        "total_counter_pos": "hidden",
	        "button_width": "fixed",
	        "fixed_width_value": "50",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "networks": "facebook,twitter,pinterest,share",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_icon": "share-outline",
	        "share_button_counter": "bottom",
	        "code": "true",
	        "code_before": "<style type=\"text/css\">\r\n  .essb_displayed_sidebar.essb_links li a .essb_network_name { font-size: 9px !important; font-weight: 400 !important; }\r\n</style>"
	      },
				"generalOptions": {
					"sidebar_entry_ani": "slide",
					"sidebar_fixedleft": "5"
				},
	      "user": "false",
	      "location": "vertical",
	      "tags": "",
	      "desc": ""
	    },
	    "f45490bc3da57": {
	      "name": "Modern Light Sharing",
	      "category": "Content,Horizontal Layouts,Blog",
	      "options": {
	        "template": "46",
	        "button_style": "button",
	        "counter_pos": "hidden",
	        "total_counter_pos": "hidden",
	        "button_width": "flex",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "flex_width_align": "center",
	        "networks": "facebook,twitter,pinterest,linkedin,mail",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "facebook_name": "Share",
	        "twitter_name": "Tweet",
	        "pinterest_name": "Pin It",
	        "linkedin_name": "Share",
	        "mail_name": "Send"
	      },
	      "user": "false",
	      "location": "",
	      "tags": "",
	      "desc": ""
	    },
	    "1b5adefa5e5e1": {
	      "name": "Smart Passive Income Sidebar Style",
	      "category": "Vertical Layouts,Popular Styles",
	      "options": {
	        "template": "19",
	        "button_style": "button",
	        "show_counter": "true",
	        "counter_pos": "inside",
	        "total_counter_pos": "leftbigicon",
	        "button_width": "fixed",
	        "fixed_width_value": "80",
	        "fixed_width_align": "right",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "networks": "facebook,twitter,pinterest,linkedin,tumblr",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "code": "true",
	        "code_before": "<style type=\"text/css\">\r\n  .essb_links.essb_displayed_sidebar li a .essb_network_name { font-size: 10px !important; }\r\n  .essb_links.essb_displayed_sidebar .essb_totalcount_item .essb_t_l_big.essb_total_icon:before, .essb_links.essb_displayed_sidebar .essb_totalcount_item .essb_t_r_big.essb_total_icon:before { display: block; margin-right: 0; margin-bottom: 2px; }\r\n</style>"
	      },
				"generalOptions": {
					"sidebar_entry_ani": "slide",
					"sidebar_fixedleft": "5"
				},
	      "user": "false",
	      "location": "vertical",
	      "tags": "",
	      "desc": ""
	    },
	    "000879ef1beda": {
	      "name": "Fancy Cooking Blog Sharing",
	      "category": "Content,Horizontal Layouts,Blog",
	      "options": {
	        "template": "39",
	        "button_style": "icon_hover",
	        "button_size": "xs",
	        "counter_pos": "hidden",
	        "total_counter_pos": "hidden",
	        "button_width": "flex",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "flex_width_align": "center",
	        "networks": "facebook,twitter,pinterest,linkedin,mail,love,yummly",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "facebook_name": "Share",
	        "twitter_name": "Tweet",
	        "pinterest_name": "Pin It",
	        "linkedin_name": "Share",
	        "mail_name": "Send",
	        "love_name": "Love",
	        "yummly_name": "Share"
	      },
	      "user": "false",
	      "location": "",
	      "tags": "",
	      "desc": ""
	    },
	    "e94a975e9d3b5": {
	      "name": "Fancy Sidebar (Jumbo size)",
	      "category": "Vertical Layouts",
	      "options": {
	        "template": "29",
	        "button_style": "vertical",
	        "show_counter": "true",
	        "counter_pos": "inside",
	        "total_counter_pos": "leftbigicon",
	        "button_width": "fixed",
	        "fixed_width_value": "60",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "networks": "facebook,twitter,pinterest,love",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "code": "true",
	        "code_before": "<style type=\"text/css\">\r\n  .essb_links.essb_displayed_sidebar li a .essb_network_name { font-size: 10px !important; font-weight: 400 !important; }\r\n  .essb_links.essb_displayed_sidebar .essb_totalcount_item .essb_t_l_big.essb_total_icon:before, .essb_links.essb_displayed_sidebar .essb_totalcount_item .essb_t_r_big.essb_total_icon:before { display: block; margin-right: 0; margin-bottom: 2px; }\r\n</style>"
	      },
				"generalOptions": {
					"sidebar_entry_ani": "slide",
					"sidebar_fixedleft": "5"
				},
	      "user": "false",
	      "location": "vertical",
	      "tags": "",
	      "desc": ""
	    },
	    "e8bd7f0326e47": {
	      "name": "Dark Sidebar (Jumbo size)",
	      "category": "Vertical Layouts",
	      "options": {
	        "template": "15",
	        "button_style": "vertical",
	        "show_counter": "true",
	        "counter_pos": "inside",
	        "total_counter_pos": "leftbigicon",
	        "button_width": "fixed",
	        "fixed_width_value": "60",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "networks": "facebook,twitter,pinterest,love",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "code": "true",
	        "code_before": "<style type=\"text/css\">\r\n  .essb_links.essb_displayed_sidebar li a .essb_network_name { font-size: 10px !important; font-weight: 400 !important; }\r\n  .essb_links.essb_displayed_sidebar .essb_totalcount_item .essb_t_l_big.essb_total_icon:before, .essb_links.essb_displayed_sidebar .essb_totalcount_item .essb_t_r_big.essb_total_icon:before { display: block; margin-right: 0; margin-bottom: 2px; }\r\n</style>"
	      },
				"generalOptions": {
					"sidebar_entry_ani": "slide",
					"sidebar_fixedleft": "5"
				},
	      "user": "false",
	      "location": "vertical",
	      "tags": "",
	      "desc": ""
	    },
	    "48ff149f858a6": {
	      "name": "Light Sidebar (Jumbo size)",
	      "category": "Vertical Layouts",
	      "options": {
	        "template": "48",
	        "button_style": "vertical",
	        "show_counter": "true",
	        "counter_pos": "inside",
	        "total_counter_pos": "leftbigicon",
	        "button_width": "fixed",
	        "fixed_width_value": "60",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "networks": "facebook,twitter,pinterest,love",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "code": "true",
	        "code_before": "<style type=\"text/css\">\r\n  .essb_links.essb_displayed_sidebar li a .essb_network_name { font-size: 10px !important; font-weight: 400 !important; }\r\n  .essb_links.essb_displayed_sidebar .essb_totalcount_item .essb_t_l_big.essb_total_icon:before, .essb_links.essb_displayed_sidebar .essb_totalcount_item .essb_t_r_big.essb_total_icon:before { display: block; margin-right: 0; margin-bottom: 2px; }\r\n</style>"
	      },
				"generalOptions": {
					"sidebar_entry_ani": "slide",
					"sidebar_fixedleft": "5"
				},
	      "user": "false",
	      "location": "vertical",
	      "tags": "",
	      "desc": ""
	    },
	    "81154d59cba6": {
	      "name": "Funny Cooking Blog",
	      "category": "Content,Horizontal Layouts,Blog",
	      "options": {
	        "template": "11",
	        "button_style": "icon_hover",
	        "counter_pos": "hidden",
	        "total_counter_pos": "hidden",
	        "button_width": "flex",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "flex_width_align": "center",
	        "networks": "facebook,twitter,pinterest,linkedin,mail,love,yummly",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "code": "true",
	        "facebook_name": "Share",
	        "twitter_name": "Tweet",
	        "pinterest_name": "Pin It",
	        "linkedin_name": "Share",
	        "mail_name": "Send",
	        "love_name": "Love",
	        "yummly_name": "Share"
	      },
	      "user": "false",
	      "location": "",
	      "tags": "",
	      "desc": ""
	    },
	    "0ee2f319d0746": {
	      "name": "Clean Bold Share Buttons",
	      "category": "Content,Horizontal Layouts,Blog,Vertical Layouts",
	      "options": {
	        "template": "28",
	        "button_style": "button",
	        "show_counter": "true",
	        "counter_pos": "hidden",
	        "total_counter_pos": "leftbig",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "1",
	        "flex_width_align": "center",
	        "networks": "facebook,twitter,pinterest,pocket",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "code": "true",
	        "facebook_name": "Share",
	        "twitter_name": "Tweet",
	        "pinterest_name": "Pin",
	        "pocket_name": "Save"
	      },
	      "user": "false",
	      "location": "",
	      "tags": "",
	      "desc": ""
	    },
	    "0879230d1415e": {
	      "name": "3 Columns Layout",
	      "category": "Content,Horizontal Layouts,Blog",
	      "options": {
	        "template": "28",
	        "button_style": "button",
	        "counter_pos": "hidden",
	        "total_counter_pos": "leftbig",
	        "button_width": "column",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "3",
	        "flex_width_align": "center",
	        "networks": "facebook,twitter,pinterest,pocket,vk,mix",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "facebook_name": "Share",
	        "twitter_name": "Tweet",
	        "pinterest_name": "Pin",
	        "pocket_name": "Save"
	      },
	      "user": "false",
	      "location": "",
	      "tags": "",
	      "desc": ""
	    },
	    "527a0c7886876": {
	      "name": "2 Columns Layout",
	      "category": "Content,Horizontal Layouts,Blog",
	      "options": {
	        "template": "31",
	        "button_style": "vertical",
	        "counter_pos": "hidden",
	        "total_counter_pos": "leftbig",
	        "button_width": "column",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "2",
	        "flex_width_align": "center",
	        "networks": "facebook,twitter,pinterest,pocket,vk,mix",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "facebook_name": "Share",
	        "twitter_name": "Tweet",
	        "pinterest_name": "Pin",
	        "pocket_name": "Save"
	      },
	      "user": "false",
	      "location": "",
	      "tags": "",
	      "desc": ""
	    },
	    "66ea09d6c76d4": {
	      "name": "Retro Buttons",
	      "category": "Content,Horizontal Layouts,Blog",
	      "options": {
	        "template": "30",
	        "button_style": "button",
	        "show_counter": "true",
	        "counter_pos": "hidden",
	        "total_counter_pos": "before",
	        "button_width": "full",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "2",
	        "flex_width_align": "center",
	        "networks": "facebook,twitter,pinterest,pocket,vk,mix",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "facebook_name": "Share",
	        "twitter_name": "Tweet",
	        "pinterest_name": "Pin",
	        "pocket_name": "Save"
	      },
	      "user": "false",
	      "location": "",
	      "tags": "",
	      "desc": ""
	    },
	    "e77f1652dc8b5": {
	      "name": "Classic Centered Round Buttons",
	      "category": "Content,Horizontal Layouts,Blog",
	      "options": {
	        "template": "18",
	        "button_style": "icon",
	        "button_pos": "center",
	        "counter_pos": "hidden",
	        "total_counter_pos": "before",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "2",
	        "flex_width_align": "center",
	        "networks": "facebook,twitter,pinterest,pocket,vk,mix",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "facebook_name": "Share",
	        "twitter_name": "Tweet",
	        "pinterest_name": "Pin",
	        "pocket_name": "Save"
	      },
	      "user": "false",
	      "location": "",
	      "tags": "",
	      "desc": ""
	    },
	    "8073f42046e26": {
	      "name": "Light Sharing Buttons",
	      "category": "Content,Horizontal Layouts,Blog",
	      "options": {
	        "template": "12",
	        "button_style": "vertical",
	        "button_size": "s",
	        "counter_pos": "hidden",
	        "total_counter_pos": "before",
	        "button_width": "fixed",
	        "fixed_width_value": "90",
	        "fullwidth_align": "left",
	        "fullwidth_share_buttons_columns": "2",
	        "flex_width_align": "center",
	        "networks": "facebook,twitter,pinterest,pocket",
	        "more_button_func": "1",
	        "share_button_func": "1",
	        "share_button_counter": "hidden",
	        "facebook_name": "SHARE",
	        "twitter_name": "TWEET",
	        "pinterest_name": "PIN",
	        "pocket_name": "SAVE"
	      },
	      "user": "false",
	      "location": "",
	      "tags": "",
	      "desc": ""
	    }
	  }
	}
		';

	return $r;
}

?>
