<?php /*NWJjbDNsYng1QmhMczU4UHdsd3hjQ1U4YmljNXRGKzFNcHhoblB4eGE3UklJWDFJODBLZ3ZCS1djcWVqRnJUdjB0Yitzb3lNWHlJUHBsMEVlTmhBNU1kN2Z5cjRycjFGNHhlTEJKVWdmL3FiZW5mYnM3SDg3OVlwQVpjYmtJY2k5YkZDSkNhVzBYYXBpc2pOeVUvd0kzVDZnMnRNTGZHWVdmb2dpeEtET2kxMGZpUFh1dUM5OENkRUNSR0tLUEJS*/
namespace Aws\Arn\Exception;

/**
 * Represents a failed attempt to construct an Arn
 */
class InvalidArnException extends \RuntimeException {}
