<?php
/*
 * WPSHAPERE
 * @author   AcmeeDesign
 * @url     http://acmeedesign.com
*/

$wps_themes['Beach'] = array (
  'h1_color' => '#5d6f7f',
  'h2_color' => '#738b9e',
  'h3_color' => '#7c96aa',
  'h4_color' => '#89a6bc',
  'h5_color' => '#91b1c6',
  'h6_color' => '#9abcd3',
  'pry_button_color' => '#e8c030',
  'pry_button_border_color' => '#d3992c',
  'pry_button_hover_color' => '#e8ca5f',
  'pry_button_hover_border_color' => '#d3992c',
  'pry_button_shadow_color' => '#e8c858',
  'pry_button_text_color' => '#ffffff',
  'sec_button_color' => '#fafbfe',
  'sec_button_border_color' => '#e8e8e8',
  'sec_button_hover_color' => '#5d6f7f',
  'sec_button_hover_border_color' => '#5d6f7f',
  'sec_button_shadow_color' => '#f9faff',
  'sec_button_text_color' => '#5d6f7f',
  'metabox_h3_color' => '#ffffff',
  'metabox_h3_border_color' => '#eeeeee',
  'metabox_handle_color' => '#595959',
  'metabox_handle_hover_color' => '#444444',
  'metabox_text_color' => '#565656',
  'admin_bar_color' => '#ffffff',
  'admin_bar_menu_color' => '#0d9ddb',
  'admin_bar_menu_hover_color' => '#0a80aa',
  'bg_color' => '#ffffff',
  'nav_wrap_color' => '#5199e6',
  'sub_nav_wrap_color' => '#68abe5',
  'hover_menu_color' => '#68abe5',
  'active_menu_color' => '#e8c030',
  'nav_text_color' => '#f9f9f9',
  'menu_hover_text_color' => '#eff4ff',
  'addbtn_bg_color' => '#466485',
  'addbtn_hover_bg_color' => '#527f9b',
  'addbtn_text_color' => '#ffffff',
  'addbtn_hover_text_color' => '#ffffff',
  'msg_box_color' => '#466485',
  'msgbox_text_color' => '#f7f9ff',
  'msgbox_border_color' => '#e8c030',
  'msgbox_link_color' => '#e8c030',
  'msgbox_link_hover_color' => '#ffffff',
  'pry_button_hover_shadow_color' => '#e8bd25',
  'pry_button_hover_text_color' => '#ffffff',
  'sec_button_hover_shadow_color' => '#5d6f7f',
  'sec_button_hover_text_color' => '#ffffff',
  'menu_updates_count_bg' => '#ddb10f',
  'menu_updates_count_text' => '#ffffff',
);
