<?php
/*
 * WPSHAPERE
 * @author   AcmeeDesign
 * @url     http://acmeedesign.com
*/

$wps_themes['Black and white'] = array (
  'h1_color' => '#0a0a0a',
  'h2_color' => '#2b2b2b',
  'h3_color' => '#474747',
  'h4_color' => '#5e5e5e',
  'h5_color' => '#727272',
  'h6_color' => '#8c8c8c',
  'pry_button_color' => '#04050a',
  'pry_button_border_color' => '#02040a',
  'pry_button_hover_color' => '#262626',
  'pry_button_hover_border_color' => '#262626',
  'pry_button_shadow_color' => '#05060a',
  'pry_button_text_color' => '#ffffff',
  'sec_button_color' => '#ffffff',
  'sec_button_border_color' => '#05020a',
  'sec_button_hover_color' => '#ffffff',
  'sec_button_hover_border_color' => '#333333',
  'sec_button_shadow_color' => '#ffffff',
  'sec_button_text_color' => '#0a0206',
  'metabox_h3_color' => '#ffffff',
  'metabox_h3_border_color' => '#eeeeee',
  'metabox_handle_color' => '#595959',
  'metabox_handle_hover_color' => '#0a0a0a',
  'metabox_text_color' => '#595959',
  'admin_bar_color' => '#ffffff',
  'admin_bar_menu_color' => '#09090a',
  'admin_bar_menu_hover_color' => '#303030',
  'bg_color' => '#ffffff',
  'nav_wrap_color' => '#ffffff',
  'sub_nav_wrap_color' => '#bdbdbf',
  'hover_menu_color' => '#d6d6d6',
  'active_menu_color' => '#a7a6a8',
  'nav_text_color' => '#0a0a0a',
  'menu_hover_text_color' => '#0a0a0a',
  'addbtn_bg_color' => '#0a0a0a',
  'addbtn_hover_bg_color' => '#333333',
  'addbtn_text_color' => '#ffffff',
  'addbtn_hover_text_color' => '#f9f9f9',
  'msg_box_color' => '#eaeaea',
  'msgbox_text_color' => '#4c4c4c',
  'msgbox_border_color' => '#07040a',
  'msgbox_link_color' => '#0a0405',
  'msgbox_link_hover_color' => '#3a3a3a',
  'pry_button_hover_shadow_color' => '#262626',
  'pry_button_hover_text_color' => '#ffffff',
  'sec_button_hover_shadow_color' => '#ffffff',
  'sec_button_hover_text_color' => '#333333',
  'menu_updates_count_bg' => '#0a0a0a',
  'menu_updates_count_text' => '#ffffff',
);
