<?php
/*
 * WPSHAPERE
 * @author   AcmeeDesign
 * @url     http://acmeedesign.com
*/

$wps_themes['Blossoms'] = array (
  'h1_color' => '#592e70',
  'h2_color' => '#49463f',
  'h3_color' => '#636055',
  'h4_color' => '#756d5b',
  'h5_color' => '#8e826f',
  'h6_color' => '#aa9785',
  'pry_button_color' => '#5783bb',
  'pry_button_border_color' => '#003f87',
  'pry_button_hover_color' => '#6795db',
  'pry_button_hover_border_color' => '#003f87',
  'pry_button_shadow_color' => '#6a93c5',
  'pry_button_text_color' => '#ffffff',
  'sec_button_color' => '#ffffff',
  'sec_button_border_color' => '#8551a5',
  'sec_button_hover_color' => '#8551a5',
  'sec_button_hover_border_color' => '#592e70',
  'sec_button_shadow_color' => '#ffffff',
  'sec_button_text_color' => '#8551a5',
  'metabox_h3_color' => '#ffffff',
  'metabox_h3_border_color' => '#eeeeee',
  'metabox_handle_color' => '#595959',
  'metabox_handle_hover_color' => '#444444',
  'metabox_text_color' => '#565656',
  'admin_bar_color' => '#e3d7e9',
  'admin_bar_menu_color' => '#af76bc',
  'admin_bar_menu_hover_color' => '#86588c',
  'bg_color' => '#eeebe5',
  'nav_wrap_color' => '#8551a5',
  'sub_nav_wrap_color' => '#683c87',
  'hover_menu_color' => '#592e70',
  'active_menu_color' => '#592e70',
  'nav_text_color' => '#e3d7e9',
  'menu_hover_text_color' => '#e3d7e9',
  'addbtn_bg_color' => '#5783bb',
  'addbtn_hover_bg_color' => '#6795db',
  'addbtn_text_color' => '#ffffff',
  'addbtn_hover_text_color' => '#ffffff',
  'msg_box_color' => '#ffffff',
  'msgbox_text_color' => '#848484',
  'msgbox_border_color' => '#8551a5',
  'msgbox_link_color' => '#2b0742',
  'msgbox_link_hover_color' => '#8551a5',
  'pry_button_hover_shadow_color' => '#5775ba',
  'pry_button_hover_text_color' => '#fcfcfc',
  'sec_button_hover_shadow_color' => '#8551a5',
  'sec_button_hover_text_color' => '#ffffff',
  'menu_updates_count_bg' => '#3c1a4c',
  'menu_updates_count_text' => '#e3d7e9',
);
