<?php
/*
 * WPSHAPERE
 * @author   AcmeeDesign
 * @url     http://acmeedesign.com
*/

$wps_themes['Blueberry'] = array (
  'h1_color' => '#697289',
  'h2_color' => '#798196',
  'h3_color' => '#868fa8',
  'h4_color' => '#9ca5c1',
  'h5_color' => '#a9afcc',
  'h6_color' => '#bec4dd',
  'pry_button_color' => '#60adf1',
  'pry_button_border_color' => '#3a99f2',
  'pry_button_hover_color' => '#48a3f2',
  'pry_button_hover_border_color' => '#3a99f2',
  'pry_button_shadow_color' => '#8bc8f6',
  'pry_button_text_color' => '#ffffff',
  'sec_button_color' => '#fafbfe',
  'sec_button_border_color' => '#c8d9e4',
  'sec_button_hover_color' => '#ffffff',
  'sec_button_hover_border_color' => '#aab6c1',
  'sec_button_shadow_color' => '#fafbfe',
  'sec_button_text_color' => '#8c96b1',
  'metabox_h3_color' => '#e8ecf5',
  'metabox_h3_border_color' => '#ced9e3',
  'metabox_handle_color' => '#68718a',
  'metabox_handle_hover_color' => '#414c75',
  'metabox_text_color' => '#68718a',
  'admin_bar_color' => '#60adf1',
  'admin_bar_menu_color' => '#e8edf9',
  'admin_bar_menu_hover_color' => '#ffffff',
  'bg_color' => '#f3f5fa',
  'nav_wrap_color' => '#727f9e',
  'sub_nav_wrap_color' => '#5b6282',
  'hover_menu_color' => '#525e7f',
  'active_menu_color' => '#60adf1',
  'nav_text_color' => '#d7dbe7',
  'menu_hover_text_color' => '#d7dbe7',
  'addbtn_bg_color' => '#60adf1',
  'addbtn_hover_bg_color' => '#48a3f2',
  'addbtn_text_color' => '#ffffff',
  'addbtn_hover_text_color' => '#ffffff',
  'msg_box_color' => '#dce1eb',
  'msgbox_text_color' => '#9ca5bc',
  'msgbox_border_color' => '#69cdbf',
  'msgbox_link_color' => '#81869e',
  'msgbox_link_hover_color' => '#69cdbf',
  'pry_button_hover_shadow_color' => '#9fcff4',
  'pry_button_hover_text_color' => '#ffffff',
  'sec_button_hover_shadow_color' => '#ffffff',
  'sec_button_hover_text_color' => '#7b829e',
  'menu_updates_count_bg' => '#414c75',
  'menu_updates_count_text' => '#d7dbe7',
);
