<?php
/*
 * WPSHAPERE
 * @author   AcmeeDesign
 * @url     http://acmeedesign.com
*/

$wps_themes['Default'] = array (
  'h1_color' => '#777777',
  'h2_color' => '#7c7c7c',
  'h3_color' => '#6b6b6b',
  'h4_color' => '#555555',
  'h5_color' => '#555555',
  'pry_button_color' => '#7ac600',
  'pry_button_hover_color' => '#29ac39',
  'pry_button_text_color' => '#ffffff',
  'sec_button_color' => '#c9c8bf',
  'sec_button_hover_color' => '#b7b6ae',
  'sec_button_text_color' => '#ffffff',
  'admin_bar_color' => '#ffffff',
  'admin_bar_menu_color' => '#94979B',
  'admin_bar_menu_hover_color' => '#474747',
  'bg_color' => '#b8f2e8',
  'nav_wrap_color' => '#282a3a',
  'sub_nav_wrap_color' => '#373b4c',
  'hover_menu_color' => '#2f313f',
  'active_menu_color' => '#6da87a',
  'nav_text_color' => '#90a1a8',
  'menu_hover_text_color' => '#ffffff',
  'h6_color' => '#555555',
  'metabox_h3_color' => '#4cbceb',
  'metabox_handle_color' => '#91f5ff',
  'metabox_handle_hover_color' => '#ffffff',
  'metabox_text_color' => '#ffffff',
  'metabox_h3_border_color' => '#46b0dd',
  'msg_box_color' => '#02c5cc',
  'msgbox_text_color' => '#ffffff',
  'msgbox_border_color' => '#007e87',
  'msgbox_link_color' => '#efefef',
  'msgbox_link_hover_color' => '#e5e5e5',
  'addbtn_bg_color' => '#53d860',
  'addbtn_text_color' => '#ffffff',
  'addbtn_hover_bg_color' => '#5ac565',
  'addbtn_hover_text_color' => '#ffffff',
  'pry_button_hover_text_color' => '#ffffff',
  'sec_button_hover_text_color' => '#ffffff',
  'pry_button_border_color' => '#86b520',
  'pry_button_shadow_color' => '#98ce23',
  'pry_button_hover_border_color' => '#259633',
  'pry_button_hover_shadow_color' => '#3d7a0c',
  'sec_button_border_color' => '#afaea5',
  'sec_button_shadow_color' => '#dbdbd0',
  'sec_button_hover_border_color' => '#a6a89e',
  'sec_button_hover_shadow_color' => '#96948b',
);
