<?php
/*
 * WPSHAPERE
 * @author   AcmeeDesign
 * @url     http://acmeedesign.com
*/

$wps_themes['Grass'] = array (
  'h1_color' => '#364c23',
  'h2_color' => '#6b904f',
  'h3_color' => '#84b262',
  'h4_color' => '#84b262',
  'h5_color' => '#96cc70',
  'h6_color' => '#a5db78',
  'pry_button_color' => '#96cc70',
  'pry_button_border_color' => '#6b904f',
  'pry_button_hover_color' => '#b2cca3',
  'pry_button_hover_border_color' => '#6b904f',
  'pry_button_shadow_color' => '#b2cca3',
  'pry_button_text_color' => '#364c23',
  'sec_button_color' => '#fafbfe',
  'sec_button_border_color' => '#76a349',
  'sec_button_hover_color' => '#76a349',
  'sec_button_hover_border_color' => '#76a349',
  'sec_button_shadow_color' => '#f9faff',
  'sec_button_text_color' => '#76a349',
  'metabox_h3_color' => '#ffffff',
  'metabox_h3_border_color' => '#ffffff',
  'metabox_handle_color' => '#595959',
  'metabox_handle_hover_color' => '#444444',
  'metabox_text_color' => '#565656',
  'admin_bar_color' => '#eeffe2',
  'admin_bar_menu_color' => '#699651',
  'admin_bar_menu_hover_color' => '#426836',
  'bg_color' => '#efefef',
  'nav_wrap_color' => '#96cc70',
  'sub_nav_wrap_color' => '#84b262',
  'hover_menu_color' => '#84b262',
  'active_menu_color' => '#6b904f',
  'nav_text_color' => '#364c23',
  'menu_hover_text_color' => '#507a34',
  'addbtn_bg_color' => '#76a349',
  'addbtn_hover_bg_color' => '#86b567',
  'addbtn_text_color' => '#ffffff',
  'addbtn_hover_text_color' => '#ffffff',
  'msg_box_color' => '#ffffff',
  'msgbox_text_color' => '#848484',
  'msgbox_border_color' => '#96cc70',
  'msgbox_link_color' => '#76a349',
  'msgbox_link_hover_color' => '#357515',
  'pry_button_hover_shadow_color' => '#82ba66',
  'pry_button_hover_text_color' => '#446b2e',
  'sec_button_hover_shadow_color' => '#76a349',
  'sec_button_hover_text_color' => '#ffffff',
  'menu_updates_count_bg' => '#364c23',
  'menu_updates_count_text' => '#ffffff',
);
