<?php
/*
 * WPSHAPERE
 * @author   AcmeeDesign
 * @url     http://acmeedesign.com
*/

$wps_themes['Hot pink'] = array (
  'h1_color' => '#dbb81e',
  'h2_color' => '#eacf00',
  'h3_color' => '#a8a8a8',
  'h4_color' => '#c1c1c1',
  'h5_color' => '#cccccc',
  'h6_color' => '#dddddd',
  'pry_button_color' => '#d3ae08',
  'pry_button_border_color' => '#6b5700',
  'pry_button_hover_color' => '#f4c713',
  'pry_button_hover_border_color' => '#6b5700',
  'pry_button_shadow_color' => '#d3ae08',
  'pry_button_text_color' => '#352000',
  'sec_button_color' => '#fafbfe',
  'sec_button_border_color' => '#c1c1c1',
  'sec_button_hover_color' => '#f2f2f2',
  'sec_button_hover_border_color' => '#adadad',
  'sec_button_shadow_color' => '#f9faff',
  'sec_button_text_color' => '#8e8e8e',
  'metabox_h3_color' => '#ffffff',
  'metabox_h3_border_color' => '#ffffff',
  'metabox_handle_color' => '#595959',
  'metabox_handle_hover_color' => '#444444',
  'metabox_text_color' => '#565656',
  'admin_bar_color' => '#3c3f3f',
  'admin_bar_menu_color' => '#f2faff',
  'admin_bar_menu_hover_color' => '#ffffff',
  'bg_color' => '#eff4f4',
  'nav_wrap_color' => '#ede221',
  'sub_nav_wrap_color' => '#f4c713',
  'hover_menu_color' => '#dbb304',
  'active_menu_color' => '#d3ae08',
  'nav_text_color' => '#6b5700',
  'menu_hover_text_color' => '#0a0a0a',
  'addbtn_bg_color' => '#d3ae08',
  'addbtn_hover_bg_color' => '#f4c713',
  'addbtn_text_color' => '#352000',
  'addbtn_hover_text_color' => '#281700',
  'msg_box_color' => '#2b3133',
  'msgbox_text_color' => '#bec4c4',
  'msgbox_border_color' => '#d3ae08',
  'msgbox_link_color' => '#d3ae08',
  'msgbox_link_hover_color' => '#af8300',
  'pry_button_hover_shadow_color' => '#f4c713',
  'pry_button_hover_text_color' => '#352000',
  'sec_button_hover_shadow_color' => '#f2f2f2',
  'sec_button_hover_text_color' => '#757575',
  'menu_updates_count_bg' => '#3c3f3f',
  'menu_updates_count_text' => '#ffffff',
);
