<?php
/*
 * WPSHAPERE
 * @author   AcmeeDesign
 * @url     http://acmeedesign.com
*/

$wps_themes['Hot pink'] = array (
  'h1_color' => '#bf004c',
  'h2_color' => '#bf3f72',
  'h3_color' => '#bf5b83',
  'h4_color' => '#bf8399',
  'h5_color' => '#d88fa7',
  'h6_color' => '#e597b4',
  'pry_button_color' => '#e26597',
  'pry_button_border_color' => '#a83e6c',
  'pry_button_hover_color' => '#e285ab',
  'pry_button_hover_border_color' => '#a83e6c',
  'pry_button_shadow_color' => '#e285a8',
  'pry_button_text_color' => '#ffffff',
  'sec_button_color' => '#fafbfe',
  'sec_button_border_color' => '#9b395a',
  'sec_button_hover_color' => '#ffffff',
  'sec_button_hover_border_color' => '#752548',
  'sec_button_shadow_color' => '#f9faff',
  'sec_button_text_color' => '#9b395a',
  'metabox_h3_color' => '#ffffff',
  'metabox_h3_border_color' => '#eeeeee',
  'metabox_handle_color' => '#9b395a',
  'metabox_handle_hover_color' => '#c14577',
  'metabox_text_color' => '#7f2c48',
  'admin_bar_color' => '#af416d',
  'admin_bar_menu_color' => '#ffffff',
  'admin_bar_menu_hover_color' => '#ea9ac0',
  'bg_color' => '#efdaed',
  'nav_wrap_color' => '#e26597',
  'sub_nav_wrap_color' => '#ce4c7c',
  'hover_menu_color' => '#d65591',
  'active_menu_color' => '#d65591',
  'nav_text_color' => '#ffffff',
  'menu_hover_text_color' => '#ffffff',
  'addbtn_bg_color' => '#752548',
  'addbtn_hover_bg_color' => '#9b2d60',
  'addbtn_text_color' => '#f9e8f2',
  'addbtn_hover_text_color' => '#f9e8f2',
  'msg_box_color' => '#e5b5ce',
  'msgbox_text_color' => '#7f2c48',
  'msgbox_border_color' => '#e26597',
  'msgbox_link_color' => '#e26597',
  'msgbox_link_hover_color' => '#7f2c48',
  'pry_button_hover_shadow_color' => '#c94c7a',
  'pry_button_hover_text_color' => '#ffffff',
  'sec_button_hover_shadow_color' => '#ffffff',
  'sec_button_hover_text_color' => '#752548',
  'menu_updates_count_bg' => '#bf004c',
  'menu_updates_count_text' => '#ffffff',
);
