<?php
/*
 * WPSHAPERE
 * @author   AcmeeDesign
 * @url     http://acmeedesign.com
*/

$wps_themes['Liquido'] = array (
  'h1_color' => '#252931',
  'h2_color' => '#313742',
  'h3_color' => '#3d4759',
  'h4_color' => '#49546d',
  'h5_color' => '#646c8c',
  'h6_color' => '#8e91af',
  'pry_button_color' => '#9328ff',
  'pry_button_border_color' => '#9328ff',
  'pry_button_hover_color' => '#2a004f',
  'pry_button_hover_border_color' => '#2a004f',
  'pry_button_shadow_color' => '#787c84',
  'pry_button_text_color' => '#ffffff',
  'pry_button_hover_shadow_color' => '#606875',
  'pry_button_hover_text_color' => '#ffffff',
  'sec_button_color' => '#bfe2ff',
  'sec_button_border_color' => '#bfe2ff',
  'sec_button_hover_color' => '#286cff',
  'sec_button_hover_border_color' => '#9328ff',
  'sec_button_shadow_color' => '#ffffff',
  'sec_button_text_color' => '#286cff',
  'sec_button_hover_text_color' => '#ffffff',
  'metabox_h3_color' => '#ffffff',
  'metabox_h3_border_color' => '#eeeeee',
  'metabox_handle_color' => '#595959',
  'metabox_handle_hover_color' => '#444444',
  'metabox_text_color' => '#565656',
  'admin_bar_color' => '#ffffff',
  'admin_bar_menu_color' => '#006d77',
  'admin_bar_menu_hover_color' => '#034147',
  'admin_bar_sbmenu_link_color' => '#006d77',
  'admin_bar_sbmenu_link_hover_color' => '#034147',
  'bg_color' => '#f1f1f1',
  'nav_wrap_color' => '#020021',
  'sub_nav_wrap_color' => '#350028',
  'sub_nav_hover_color' => '#38284b',
  'nav_text_color' => '#31878c',
  'menu_hover_text_color' => '#cfd2d7',
  'hover_menu_color' => '#38284b',
  'active_menu_color' => '#84DCCF',
  'menu_active_text_color' => '#130021',
  'addbtn_bg_color' => '#bfe2ff',
  'addbtn_hover_bg_color' => '#9328ff',
  'addbtn_text_color' => '#286cff',
  'addbtn_hover_text_color' => '#ffffff',
  'msg_box_color' => '#dde5ee',
  'msgbox_text_color' => '#202e47',
  'msgbox_border_color' => '#dde5ee',
  'msgbox_link_color' => '#4290ff',
  'msgbox_link_hover_color' => '#28416e',
  'notice_box_color' => '#e3bbbb',
  'notice_text_color' => '#f00033',
  'notice_link_color' => '#4290ff',
  'notice_link_hover_color' => '#28416e',
  'menu_updates_count_bg' => '#2d2d2d',
  'menu_updates_count_text' => '#ffffff',
);
