<?php
/*
 * WPSHAPERE
 * @author   AcmeeDesign
 * @url     http://acmeedesign.com
*/

$wps_themes['Mint'] = array (
  'h1_color' => '#0e4349',
  'h2_color' => '#739e99',
  'h3_color' => '#7caaa3',
  'h4_color' => '#87baaf',
  'h5_color' => '#94ccbd',
  'h6_color' => '#9ad3c5',
  'pry_button_color' => '#39dcad',
  'pry_button_border_color' => '#2fb791',
  'pry_button_hover_color' => '#62dbb9',
  'pry_button_hover_border_color' => '#2fb791',
  'pry_button_shadow_color' => '#62dbb9',
  'pry_button_text_color' => '#ffffff',
  'sec_button_color' => '#fafbfe',
  'sec_button_border_color' => '#d3d3d3',
  'sec_button_hover_color' => '#7f7f7f',
  'sec_button_hover_border_color' => '#7f7f7f',
  'sec_button_shadow_color' => '#f9faff',
  'sec_button_text_color' => '#7f7f7f',
  'metabox_h3_color' => '#ffffff',
  'metabox_h3_border_color' => '#eeeeee',
  'metabox_handle_color' => '#595959',
  'metabox_handle_hover_color' => '#444444',
  'metabox_text_color' => '#565656',
  'admin_bar_color' => '#2fb791',
  'admin_bar_menu_color' => '#ffffff',
  'admin_bar_menu_hover_color' => '#cbf2e4',
  'bg_color' => '#e5e5e5',
  'nav_wrap_color' => '#ffffff',
  'sub_nav_wrap_color' => '#7fdbc1',
  'hover_menu_color' => '#39dcad',
  'active_menu_color' => '#39dcad',
  'nav_text_color' => '#545454',
  'menu_hover_text_color' => '#eff3ff',
  'addbtn_bg_color' => '#2fb791',
  'addbtn_hover_bg_color' => '#55c1a3',
  'addbtn_text_color' => '#ffffff',
  'addbtn_hover_text_color' => '#ffffff',
  'msg_box_color' => '#39dcad',
  'msgbox_text_color' => '#e3f4f0',
  'msgbox_border_color' => '#2fb791',
  'msgbox_link_color' => '#ffffff',
  'msgbox_link_hover_color' => '#14725e',
  'pry_button_hover_shadow_color' => '#39dcad',
  'pry_button_hover_text_color' => '#ffffff',
  'sec_button_hover_shadow_color' => '#7f7f7f',
  'sec_button_hover_text_color' => '#ffffff',
  'menu_updates_count_bg' => '#2fb791',
  'menu_updates_count_text' => '#ffffff',
);
