<?php
/*
 * WPSHAPERE
 * @author   AcmeeDesign
 * @url     http://acmeedesign.com
*/

$wps_themes['Paper and clay'] = array (
  'h1_color' => '#281e02',
  'h2_color' => '#3d2d01',
  'h3_color' => '#4c2d00',
  'h4_color' => '#603c10',
  'h5_color' => '#755227',
  'h6_color' => '#96734e',
  'pry_button_color' => '#7a4100',
  'pry_button_border_color' => '#4f2b00',
  'pry_button_hover_color' => '#774d23',
  'pry_button_hover_border_color' => '#4f2b00',
  'pry_button_shadow_color' => '#7a4e1d',
  'pry_button_text_color' => '#ffffff',
  'sec_button_color' => '#fafbfe',
  'sec_button_border_color' => '#d3c9c9',
  'sec_button_hover_color' => '#7f7171',
  'sec_button_hover_border_color' => '#7f7676',
  'sec_button_shadow_color' => '#f9faff',
  'sec_button_text_color' => '#7f7171',
  'metabox_h3_color' => '#ffffff',
  'metabox_h3_border_color' => '#eeeeee',
  'metabox_handle_color' => '#595959',
  'metabox_handle_hover_color' => '#444444',
  'metabox_text_color' => '#565656',
  'admin_bar_color' => '#ba9f86',
  'admin_bar_menu_color' => '#ffffff',
  'admin_bar_menu_hover_color' => '#f4e9cd',
  'bg_color' => '#f2e5d7',
  'nav_wrap_color' => '#e0d0c0',
  'sub_nav_wrap_color' => '#ccb8a3',
  'hover_menu_color' => '#ccb7a1',
  'active_menu_color' => '#baa48f',
  'nav_text_color' => '#4f380b',
  'menu_hover_text_color' => '#281e02',
  'addbtn_bg_color' => '#7a4100',
  'addbtn_hover_bg_color' => '#77522c',
  'addbtn_text_color' => '#ffffff',
  'addbtn_hover_text_color' => '#ffffff',
  'msg_box_color' => '#ddc9b8',
  'msgbox_text_color' => '#4f2b00',
  'msgbox_border_color' => '#4f2b00',
  'msgbox_link_color' => '#ffffff',
  'msgbox_link_hover_color' => '#3a2600',
  'pry_button_hover_shadow_color' => '#5b3209',
  'pry_button_hover_text_color' => '#ffffff',
  'sec_button_hover_shadow_color' => '#7f7070',
  'sec_button_hover_text_color' => '#ffffff',
  'menu_updates_count_bg' => '#70583b',
  'menu_updates_count_text' => '#f2e5d7',
);
