<?php
/*
 * WPSHAPERE
 * @author   AcmeeDesign
 * @url     http://acmeedesign.com
*/

$wps_themes['Sailer'] = array (
  'h1_color' => '#02162b',
  'h2_color' => '#13253a',
  'h3_color' => '#253a4f',
  'h4_color' => '#394d5e',
  'h5_color' => '#354d77',
  'h6_color' => '#5e7396',
  'pry_button_color' => '#245bc9',
  'pry_button_border_color' => '#02127c',
  'pry_button_hover_color' => '#678ddb',
  'pry_button_hover_border_color' => '#02127c',
  'pry_button_shadow_color' => '#4c79d3',
  'pry_button_text_color' => '#eff3ff',
  'sec_button_color' => '#f7f7f7',
  'sec_button_border_color' => '#d3d3d3',
  'sec_button_hover_color' => '#7f7f7f',
  'sec_button_hover_border_color' => '#7f7f7f',
  'sec_button_shadow_color' => '#f9faff',
  'sec_button_text_color' => '#7f7f7f',
  'metabox_h3_color' => '#ffffff',
  'metabox_h3_border_color' => '#eeeeee',
  'metabox_handle_color' => '#595959',
  'metabox_handle_hover_color' => '#444444',
  'metabox_text_color' => '#565656',
  'admin_bar_color' => '#ffffff',
  'admin_bar_menu_color' => '#434b6b',
  'admin_bar_menu_hover_color' => '#292942',
  'bg_color' => '#ffffff',
  'nav_wrap_color' => '#eaedef',
  'sub_nav_wrap_color' => '#c5cdd6',
  'hover_menu_color' => '#ffffff',
  'active_menu_color' => '#245bc9',
  'nav_text_color' => '#434b6b',
  'menu_hover_text_color' => '#434b6b',
  'addbtn_bg_color' => '#245bc9',
  'addbtn_hover_bg_color' => '#4483e2',
  'addbtn_text_color' => '#f2f4fc',
  'addbtn_hover_text_color' => '#ffffff',
  'msg_box_color' => '#eaedef',
  'msgbox_text_color' => '#434b6b',
  'msgbox_border_color' => '#245bc9',
  'msgbox_link_color' => '#2a3044',
  'msgbox_link_hover_color' => '#245bc9',
  'pry_button_hover_shadow_color' => '#49649b',
  'pry_button_hover_text_color' => '#e8f9f9',
  'sec_button_hover_shadow_color' => '#7f7f7f',
  'sec_button_hover_text_color' => '#ffffff',
  'menu_updates_count_bg' => '#4e77c9',
  'menu_updates_count_text' => '#f2fffb',
);
