<?php
/*
 * WPSHAPERE
 * @author   AcmeeDesign
 * @url     http://acmeedesign.com
*/

$wps_themes['Slate'] = array (
  'h1_color' => '#252931',
  'h2_color' => '#313742',
  'h3_color' => '#3d4759',
  'h4_color' => '#49546d',
  'h5_color' => '#646c8c',
  'h6_color' => '#8e91af',
  'pry_button_color' => '#5b606d',
  'pry_button_border_color' => '#353d42',
  'pry_button_hover_color' => '#717a8c',
  'pry_button_hover_border_color' => '#353d42',
  'pry_button_shadow_color' => '#787c84',
  'pry_button_text_color' => '#ffffff',
  'sec_button_color' => '#ffffff',
  'sec_button_border_color' => '#5b606d',
  'sec_button_hover_color' => '#5b606d',
  'sec_button_hover_border_color' => '#5b606d',
  'sec_button_shadow_color' => '#ffffff',
  'sec_button_text_color' => '#5b606d',
  'metabox_h3_color' => '#ffffff',
  'metabox_h3_border_color' => '#eeeeee',
  'metabox_handle_color' => '#595959',
  'metabox_handle_hover_color' => '#444444',
  'metabox_text_color' => '#565656',
  'admin_bar_color' => '#2a2e35',
  'admin_bar_menu_color' => '#b7bbcc',
  'admin_bar_menu_hover_color' => '#ffffff',
  'bg_color' => '#eaeef2',
  'nav_wrap_color' => '#5b606d',
  'sub_nav_wrap_color' => '#252931',
  'hover_menu_color' => '#3d434d',
  'active_menu_color' => '#3d434d',
  'nav_text_color' => '#cfd2d7',
  'menu_hover_text_color' => '#cfd2d7',
  'addbtn_bg_color' => '#ffffff',
  'addbtn_hover_bg_color' => '#353d42',
  'addbtn_text_color' => '#353d42',
  'addbtn_hover_text_color' => '#ffffff',
  'msg_box_color' => '#5b606d',
  'msgbox_text_color' => '#cfd2d7',
  'msgbox_border_color' => '#252931',
  'msgbox_link_color' => '#e6eaef',
  'msgbox_link_hover_color' => '#252931',
  'pry_button_hover_shadow_color' => '#606875',
  'pry_button_hover_text_color' => '#fcfcfc',
  'sec_button_hover_shadow_color' => '#5b606d',
  'sec_button_hover_text_color' => '#ffffff',
  'menu_updates_count_bg' => '#2d2d2d',
  'menu_updates_count_text' => '#ffffff',
);
