<?php
/*
 * WPSHAPERE
 * @author   AcmeeDesign
 * @url     http://acmeedesign.com
*/

$wps_themes['Sleek'] = array (
  'h1_color' => '#20222e',
  'h2_color' => '#282c37',
  'h3_color' => '#313541',
  'h4_color' => '#434554',
  'h5_color' => '#636875',
  'h6_color' => '#8c9099',
  'pry_button_color' => '#e84a4a',
  'pry_button_border_color' => '#e84a4a',
  'pry_button_hover_color' => '#e84e4e',
  'pry_button_hover_border_color' => '#e84a4a',
  'pry_button_shadow_color' => '#ff5e5e',
  'pry_button_text_color' => '#ffffff',
  'sec_button_color' => '#c8a5a5',
  'sec_button_border_color' => '#c8a5a5',
  'sec_button_hover_color' => '#c8a5a5',
  'sec_button_hover_border_color' => '#c8a5a5',
  'sec_button_shadow_color' => '#bc9d9d',
  'sec_button_text_color' => '#ffffff',
  'metabox_h3_color' => '#ffffff',
  'metabox_h3_border_color' => '#e2e7ec',
  'metabox_handle_color' => '#8e96a0',
  'metabox_handle_hover_color' => '#787e87',
  'metabox_text_color' => '#8e96a0',
  'admin_bar_color' => '#1c1e26',
  'admin_bar_menu_color' => '#bfc3c9',
  'admin_bar_menu_hover_color' => '#efefef',
  'bg_color' => '#f4f7fa',
  'nav_wrap_color' => '#282c37',
  'sub_nav_wrap_color' => '#20222e',
  'hover_menu_color' => '#313541',
  'active_menu_color' => '#e84a4a',
  'nav_text_color' => '#e2e2e2',
  'menu_hover_text_color' => '#cecece',
  'addbtn_bg_color' => '#8e96a0',
  'addbtn_hover_bg_color' => '#a3aeb7',
  'addbtn_text_color' => '#ffffff',
  'addbtn_hover_text_color' => '#dae3e5',
  'msg_box_color' => '#62be8b',
  'msgbox_text_color' => '#ffffff',
  'msgbox_border_color' => '#165b34',
  'msgbox_link_color' => '#1f7547',
  'msgbox_link_hover_color' => '#3a8e60',
  'pry_button_hover_shadow_color' => '#d14242',
  'pry_button_hover_text_color' => '#ffffff',
  'sec_button_hover_shadow_color' => '#9ea59b',
  'sec_button_hover_text_color' => '#ffffff',
  'menu_updates_count_bg' => '#e84a4a',
  'menu_updates_count_text' => '#ffffff',
);
