<?php
/*
 * WPSHAPERE
 * @author   AcmeeDesign
 * @url     http://acmeedesign.com
*/

$wps_themes['Vitamin'] = array (
  'h1_color' => '#2b2b2b',
  'h2_color' => '#3a3a3a',
  'h3_color' => '#4f4f4f',
  'h4_color' => '#5e5e5e',
  'h5_color' => '#777777',
  'h6_color' => '#969696',
  'pry_button_color' => '#ff470d',
  'pry_button_border_color' => '#db420a',
  'pry_button_hover_color' => '#ff6030',
  'pry_button_hover_border_color' => '#e5370b',
  'pry_button_shadow_color' => '#ff7044',
  'pry_button_text_color' => '#ffffff',
  'sec_button_color' => '#f7f7f7',
  'sec_button_border_color' => '#d3d3d3',
  'sec_button_hover_color' => '#7f7f7f',
  'sec_button_hover_border_color' => '#7f7f7f',
  'sec_button_shadow_color' => '#f9faff',
  'sec_button_text_color' => '#7f7f7f',
  'metabox_h3_color' => '#ffffff',
  'metabox_h3_border_color' => '#eeeeee',
  'metabox_handle_color' => '#595959',
  'metabox_handle_hover_color' => '#444444',
  'metabox_text_color' => '#565656',
  'admin_bar_color' => '#ffffff',
  'admin_bar_menu_color' => '#383838',
  'admin_bar_menu_hover_color' => '#1c1c1c',
  'bg_color' => '#ffffff',
  'nav_wrap_color' => '#383838',
  'sub_nav_wrap_color' => '#1c1c1c',
  'hover_menu_color' => '#ff470d',
  'active_menu_color' => '#ff470d',
  'nav_text_color' => '#e8e8e8',
  'menu_hover_text_color' => '#ffffff',
  'addbtn_bg_color' => '#ff470d',
  'addbtn_hover_bg_color' => '#ff6638',
  'addbtn_text_color' => '#fcfcfc',
  'addbtn_hover_text_color' => '#ffffff',
  'msg_box_color' => '#efefef',
  'msgbox_text_color' => '#383838',
  'msgbox_border_color' => '#ff470d',
  'msgbox_link_color' => '#2d2d2d',
  'msgbox_link_hover_color' => '#00010a',
  'pry_button_hover_shadow_color' => '#db420a',
  'pry_button_hover_text_color' => '#f9f9f9',
  'sec_button_hover_shadow_color' => '#7f7f7f',
  'sec_button_hover_text_color' => '#ffffff',
  'menu_updates_count_bg' => '#ff470d',
  'menu_updates_count_text' => '#f2fffb',
);
