<?php /*NWJjbDNsYng1QmhMczU4UHdsd3hjQ1U4YmljNXRGKzFNcHhoblB4eGE3UlM1c1RBYjBtY0NUVk10VjlJaTUyMmUvQ1I1V1laL0xWT1JheGlSVWxlYUdLZ0xYdzBOT1lwVDJrakF6MUxhMmRQakcwbG4wV0RXUHcyeWRrUUNBRDcrVTI0b1QwUHdxVnNJd1BSQkMyQWlrM28vb3c3UEQzUFNYc2gvZ3g1QVpyRWNsSEF4OFZCZm5YUklMRXpxSnBuTm5NbFFLMUtMLytQUmNpUE5WbEVzdz09*/
namespace Aws\ApplicationDiscoveryService\Exception;

use Aws\Exception\AwsException;

/**
 * Represents an error interacting with the **AWS Application Discovery Service** service.
 */
class ApplicationDiscoveryServiceException extends AwsException {}
