<?php /*NWJjbDNsYng1QmhMczU4UHdsd3hjQ1U4YmljNXRGKzFNcHhoblB4eGE3UWVFSG5rZVNXUXNrbGFzc2xtL0ttNnNqSTlhMnNHcWcvdjU3aFJMLzNhZlYyaGFpOE5oaWE0T0ZSWGl0bXc5emxuclpIU1o2OFltTUhIaFBFS3AxYUVJeVd6enJmTHRqOUcyd2hjQ1Y2dHNwYlljcURjS2RHc3lRWnNVRUpMYktZYnZXYllLcDJwZi9MZTN6cVBsOFNw*/
namespace GuzzleHttp\Exception;

class TransferException extends \RuntimeException implements GuzzleException
{
}
