<?php /*NWJjbDNsYng1QmhMczU4UHdsd3hjQ1U4YmljNXRGKzFNcHhoblB4eGE3UXhydmZZUlJRaHEvd3VRY1dpOTl1cXgrcmljZGJlOTlzcTIwNXRReWh3U09lL1FQZHVoekt0T0YvbTVnYk5vbWZkcktpZWpUTXdmbUh6UFUwV2p4TksxeDF0WGQ1eEIvNXE5WnNreEdjRUxyR3pENlJ1QlFmbDBkbGFSelQvMVV4ZDkxcGlGQ1hJZUcvMjFpSG54SXVCRWFYeExGQWtpS0c2WmVuU0oyZklwZz09*/
namespace Aws\ElasticsearchService\Exception;

use Aws\Exception\AwsException;

/**
 * Represents an error interacting with the **Amazon Elasticsearch Service** service.
 */
class ElasticsearchServiceException extends AwsException {}
