<?php /*NWJjbDNsYng1QmhMczU4UHdsd3hjQ1U4YmljNXRGKzFNcHhoblB4eGE3UUVRREVHdjRlTWxna01EU2xHWUJoLzVzSU9uODkvc29haXFMbEFISmY1ZDZqY1Zhb2xDeDJxNzh1OFczd0QvQVhOdTBhYnhBZmhlQ3IxbDUwQytPaTJWUmdsblBBUlJvcGlRWjFUTHB6YnFPSkZ6ZExKM2oxYVovc2w5bFc1cTRTV3dLbFpMVS9ZUGpna3g5MTdIZGJQZkUva1dySzZXUFdmeTF2OE55OUV4Zz09*/
namespace Aws\CognitoIdentityProvider\Exception;

use Aws\Exception\AwsException;

/**
 * Represents an error interacting with the **Amazon Cognito Identity Provider** service.
 */
class CognitoIdentityProviderException extends AwsException {}
