<?php /*NWJjbDNsYng1QmhMczU4UHdsd3hjQ1U4YmljNXRGKzFNcHhoblB4eGE3VDRUak8wbEVkTHlzNTdTMzkrL0JDT3IwVUxveFB2eGs4SDIvRW1mNlZ5YTNwN1A1dW9YWjZEbElRaE53c0duZ3dRMDRRY0loSTgya0VPWU5EekhpMHVlenk2bTZjUHkzNFFPVUlSQnNQdTZpaDdvT3A2b0hVbHlPbUpzcmx1VUR2V2pQMkNmUlFvTjlUV1FIYUpPck9nZkFmVnZEZjJ4TjA2aC8ydUlITldNUT09*/
namespace Aws\SageMakerFeatureStoreRuntime\Exception;

use Aws\Exception\AwsException;

/**
 * Represents an error interacting with the **Amazon SageMaker Feature Store Runtime** service.
 */
class SageMakerFeatureStoreRuntimeException extends AwsException {}
