<?php /*NWJjbDNsYng1QmhMczU4UHdsd3hjQ1U4YmljNXRGKzFNcHhoblB4eGE3UkZMU3pHUXBJRWVBQlhxT2tPVmR3UzU4c1o4S2RYTDFiTUU3YnZYWEdKMEdpTmk3N2xWZURNOTZkM01rWGJ4UnBUblhWY2VmSW9Rc1F5MENiRmgzdzhEWk54dHJoMlRLSE8raGdpL0NwUm9ORGY0ZmpYSzZ5YnkvT1gyQkprL0VKQ0tVNjV6cTdlenFlTUZpVEJuRlV3ZmpQRFd4d3FBdzQzbkNyOUJXQ3EzQT09*/
namespace Aws\MarketplaceMetering\Exception;

use Aws\Exception\AwsException;

/**
 * Represents an error interacting with the **AWSMarketplace Metering** service.
 */
class MarketplaceMeteringException extends AwsException {}
